name: CI

on:
    push:
        branches: [master, "feature/*"]
    pull_request:
        branches: [master, "feature/*"]
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

env:
    MACOSX_DEPLOYMENT_TARGET: "11.0"

jobs:
    ffi_32bit_build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-rust
              with:
                  target: armv7-unknown-linux-gnueabihf
            - uses: baptiste0928/cargo-install@v3
              with:
                  crate: cross
            - name: Check
              run: cross check --target=armv7-unknown-linux-gnueabihf -p slint-cpp --no-default-features --features=testing,interpreter,std,backend-qt,compat-1-2
